export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const SET_SEARCH = "SET_SEARCH";
export const SET_FILTER = "SET_FILTER";
export const UPDATE_PRODUCT_ADD = "UPDATE_PRODUCT_ADD";
export const UPDATE_PRODUCT_REMOVE = "UPDATE_PRODUCT_REMOVE";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
